### PR TITLE
Fixed and cleaned up Pornhub video ripper

### PR DESCRIPTION
**Pull request by buzzlightmonth**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [x] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [ ] a new feature

# Description

The Pornhub video ripper was not working anymore, it tried using a regex to match a JSON array which was not very clean.

I made it so that it directly uses the JSON array and it now works as far as I can tell.
Also, the quality is now included in the filenames.

The only test failures used to exist before my fix, and don't concern this ripper.

Fixes issue #1095 

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by buzzlightmonth** [comment]
Okay so it turns out this works alright when the ripper is run with the GUI but not from the command line...

Since I am not that familiar with the code, I have no idea why this behaviour is any different. It might be because of escaping slashes in the command line?

**Comment by buzzlightmonth** [comment]
After a little debugging, it turns out that my fix does work, except on certain URLs Pornhub will show a "loading.." message... I have no idea how to fix this. It has nothing to do with my fix though.

**Comment by cyian-1756** [comment]
Looks good to me. Heads up about future PRs, put the issue it closes next to the "a bug fix (Fix #" so that when I merge the mentioned issue will be auto closed

**Comment by buzzlightmonth** [comment]
> Heads up about future PRs, put the issue it closes next to the "a bug fix (Fix #" so that when I merge the mentioned issue will be auto closed
Okay thanks for the heads up!
I was wondering also, what am I supposed to do with my fork when the master here has new updates pulled into it?
I feel like doing a PR in my fork is a bad idea since when I will do a PR here again there will be commits saying I merged this master into my fork...

**Comment by cyian-1756** [comment]
> I was wondering also, what am I supposed to do with my fork when the master here has new updates pulled into it?

Pull the updates to your fork

> I feel like doing a PR in my fork is a bad idea since when I will do a PR here again there will be commits saying I merged this master into my fork...

Just pull from ripmeapp/ripme master on your forks master branch 

[Here's an SO answer detailing how ](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)

**Comment by buzzlightmonth** [comment]
Right, but that will add merge commits that will intervene when I make another PR, no?

**Comment by buzzlightmonth** [comment]
The rebase solution fixed it, thanks! It's not very intuitive, and it can't be done online with the GitHub UI...

**Pull request merged**
