### PR TITLE
Instagram ripper renewed

### PR DESCRIPTION
**Pull request by taurhel**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [x] a bug fix
* [ ] a new Ripper
* [x] a refactoring
* [ ] a style change/fix
* [x] a new feature (#1301, #508, #205)

# Description

Fixed tag ripping.
Added support for TAGGED, IGTV, STORIES, PINNED items.
'sessionid' cookie support for stories and private rips.

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
Testing this out with https://www.instagram.com/hd._cloutt/ it fails to rip all files

**Comment by taurhel** [comment]
> Testing this out with https://www.instagram.com/hd._cloutt/ it fails to rip all files

It won't download preview images for all videos except stories. Everything else looks fine.
Not sure if it should be fixed.

**Comment by Isaaku** [comment]
@cyian-1756 What do you see that fails? 
@taurhel You could also add a option to download story/pinned/igtv/tagged when the url is from a profile?. Also you should reference the issues #200 #970 since you implemented the setAuthCookie() method

**Comment by cyian-1756** [comment]
@Isaaku 

> What do you see that fails?

It was just the video preview images

**Pull request merged**
