### PR TITLE
eroshare regex now allows for www to appear before the domain and eroshare ripper no longer adds extra https: to eroshare links

### LINKED ISSUE #39: TODO: Clean up EroShareRipper
As mentioned in comments on PR #29

@cyian-1756 FYI

### PR DESCRIPTION
**Pull request by cyian-1756**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [X] a bug fix (Fix #39 )
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix

# Description

Minor change to the url matching regex

# Testing

Required verification:
* [X] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [X] I've verified that this change works as intended.
  * [X] Downloads all relevant content.
  * [X] Downloads content from multiple pages (as necessary or appropriate).
  * [X] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [X] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by rautamiekka** [comment]
IMO we should make the `r` in `share` optional in case the original domain comes back.

**Comment by cyian-1756** [comment]
> IMO we should make the r in share part of the domain optional in case the original domain comes back.

What would that fix? At this point the ripper already matches both eroshare and eroshae

**Comment by rautamiekka** [comment]
^ Well, for instance, less of the self-repeating Java code.

**Comment by metaprime** [comment]
@cyian-1756: @rautamiekka makes a good point. Most of the code between eroshae and eroshare is a direct duplicate, and using the regex eroshar?e would allow most codepaths to be refactored.

However, that's out of scope of this change.

This change looks good to me as-is.

**Pull request closed without merging**
