### PR TITLE
Added support for SOCKS v5 Server

### PR DESCRIPTION
**Pull request by randomcommitter**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [x] an enhancement (See #285 but only partially)

# Description

Sorry for my horrible Java skills, but this adds basic support for SOCKS v5 servers on CLI

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
This looks good to me, I'll merge it in for the next release of ripme. In the mean time it would be nice if you added a unit test (Just hit icanhazip.com before and after setting the proxy and make sure the returned data is different) and/or the ability to set the proxy via config file

**Comment by cyian-1756** [comment]
@randomcommitter 

> I could do the unit test but I don't know any free socks servers which are reliable enough to be put in a test case

In that case just do something like

```java

socks_proxy ="";

if (!socks_proxy.equals("")) {
    // Unit test goes here
}
```

That way if anyone ever wants to test this they can just find a free socks proxy or just enter their own.

**Comment by thinkpad4** [comment]
@cyian-1756 don't forget to add this to the config section of the wiki

**Comment by cyian-1756** [comment]
@thinkpad4 This doesn't have a config entry yet (It's currently just a commandline option) but it's on the todo list

**Pull request merged**
