### PR TITLE
Updated TravisCI configuration

### PR DESCRIPTION
**Pull request by MrTimscampi**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [x] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix

# Description

Changes the TravisCI configuration to make it work on the current environment and build against OpenJDK8 and Oracle JDK8 (In order to ensure that everyone can use it and to be able to spot JVM-related bugs quicker).

This was tested using my account, you can read the logs there: https://travis-ci.org/MrTimscampi/ripme  
Note that the builds fail due to unit tests failing, but the build completes (which is what is important, at this stage).

A member of the RipMeApp organization should enable Travis (Easy to do, just go login on TravisCI and enable the repo) to complete this PR.

Another change that would be interesting but can only be done by someone from the organization is to enable Travis to deploy releases on GitHub.  
This would enable a contributor to tag a commit with the version number before a push, then Travis would automatically build, test and publish a release on GitHub.  
Instructions can be found here: https://docs.travis-ci.com/user/deployment/releases/

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
> Easy to do, just go login on TravisCI and enable the repo

Doesn't the repo owner (@metaprime for this repo) have to be the one who enables TravisCI? I ask because I was going to do this earlier but the only repos I was allowed to enable TravisCI for where ones I owned

**Comment by MrTimscampi** [comment]
It depends on the permissions of the organization, maybe ?

I know that you need to enable third party integration for the Organization itself to be able to see it in other tools like TravisCI, so that may be it as well.

But yeah, metaprime is maybe the one who needs to do it.

**Comment by cyian-1756** [comment]
> Edit: By going to Account > "Review and add" on TravisCI, you can check the permissions and enable TravisCI for the organization, if not done yet.

I sent a approval request to @metaprime

**Comment by metaprime** [comment]
I've activated RipMeApp/ripme on Travis-CI

**Comment by metaprime** [comment]
Closed and reopened this PR to trigger a build. Also opened #159 to test the build before this PR's changes.

**Comment by metaprime** [comment]
LGTM. Merging.

**Pull request merged**
