### PR TITLE
VSCO Ripper

### PR DESCRIPTION
**Pull request by kevin51jiang**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix (Fix #...)
* [X] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix

# Description

Added VSCO Ripper suggested in #38.
Currently only supports ripping single images, pushing this out ASAP in case someone needs it.

The problem right now is with the Javascript changing the DOM, so Jsoup does not work properly. Maybe this will have to be a JSON ripper?

# Testing

Required verification:
* [X] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [X] I've verified that this change works as intended.
  * [X] Downloads all relevant content.
  * [X] Downloads content from multiple pages (as necessary or appropriate).
  * [X] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [X] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [X] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
This looks good aside from some style issues. Replace all the `}else{`s with `} else {` and `if(`s with `if (` and I'll merge it

**Comment by kevin51jiang** [comment]
@cyian-1756 

Done

**Comment by cyian-1756** [comment]
Code looks good to me and travis seems to be failing for an unrelated reason (Looks like ripme froze at some point, because the tests lasted for more than 6 hours)

I'll merge this in for 1.7.14

**Comment by kevin51jiang** [comment]
I think Travis had some sort of problem yesterday, the tests on my fork were 6hrs as well.

**Pull request merged**
