### PR TITLE
Update to Java 8

### PR DESCRIPTION
**Pull request by MrTimscampi**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix (Fix #...)
* [ ] a new Ripper
* [x] a refactoring
* [ ] a style change/fix

# Description

* Changed the Maven target to 1.8
* Performed a preliminary cleanup using IntelliJ's Code Analysis (Only Java 7/8 updates and a few other entries in the Error and Warnings categories)
* Updated the readme to change the required Java version

It all seems to work just like before.  
Note that this is a preliminary semi-automated cleanup, more manual updates and refactoring is likely needed.  
It was also rebased before the PR, as there was some conflicts. It's my first rebase, so I may have messed up some stuff. It was tested (both unit tests and manually) afterwards, so it works, but it may re-commit some already commited stuff.

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by PaulBGD** [comment]
I like the idea, but any reason you changed all the public methods/classes to private so that they can't be used as an API?

**Comment by MrTimscampi** [comment]
They aren't used anywhere where being public is necessary, so it's mainly for consistency.

The changes where suggested by the code analysis according to the current code, so I can change them if needed, but as they're not being used as an API currently (As said, the software still tests and runs as it did before), it doesn't really make sense to have them Public "just in case".

Same for the few functions I switched to Protected.

My usual way to go is do grant as few permissions and access to things as possible.

As said, if this is too much of a change, I can make another commit to fix it, but there's no reason to keep these public as far as I know.

**Comment by cyian-1756** [comment]
Giving this a quick look over it all seems alright, and mvn test doesn't come up with any new errors

@MrTimscampi 

In the future try to stick to one change per PR (Update everything to java 8 in one, the changes from public to private in another, the changes to rippers in another ect). It makes everything much easier to fix if anything breaks

**Comment by MrTimscampi** [comment]
@cyian-1756 Will do that next time :)

**Pull request merged**
