### PR TITLE
Gfy cat url j unit fix

### PR DESCRIPTION
**Pull request by kevin51jiang**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [X] a bug fix (Fix #358 )
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix

# Description

Slight optimization for Gfycat URLS:
     Instead of:    Replace "/gifs/details/ with "/"
               now: Replace "/gifs/details" with ""

Removed Gfycat tests. It works locally but I don't know about JUnit to write proper tests.

# Testing

Required verification:
* [X] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [X] I've verified that this change works as intended.
  * [X] Downloads all relevant content.
  * [X] Downloads content from multiple pages (as necessary or appropriate).
  * [X] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [X] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by fearme123123** [comment]
It didn't fix it for me :/ It won't download some of the files for some reason.

**Comment by kevin51jiang** [comment]
Can you tell me which ones? It's worked all the times I've tried it so far.

**Comment by fearme123123** [comment]
https://www.reddit.com/user/seemewithemhands/submitted/

I'm downloading this one, but it gives me a lot of error when downloading some of the vids.

**Comment by kevin51jiang** [comment]
To other people browsing: NSFW.

[`Single Image (direct link to gfycat) seems to work fine`](https://i.imgur.com/9ss6jmZ.png) Even with the "/gifs/detail"

[The ones with /gifs/detail can't work](https://i.imgur.com/rYUZEJM.png) 
[But normally formatted links can](https://i.imgur.com/9eu5zCU.png)

I'm going to assume that the reddit ripper doesn't sanitize the URL, but I'll look into it further.

**Comment by fearme123123** [comment]
Any update? 👍 Did you find a way to make it work?

**Comment by kevin51jiang** [comment]
@fearme123123 

In /src/com.rarchives.ripme.utils/RipUtils.java (which is what I imagine the Reddit ripper uses), they try to fetch & download a video from GfyCat **without creating a new object.**

This meant that the sanitation method would not have been called. This is also why if you just tried with a nicely formatted link, or a Gfycat link by itself it would work, but if you shoved a reddit link in it with a bad URL it would crap its pants.

Very disappointed in myself right now.

Fix should be coming sometime tomorrow, it's pretty late right now for me.

**Comment by fearme123123** [comment]
Oh yeah, I figured it didn't create a new object since the error message occures when the file size was 0.
Thanks for the fix mate :)

**Comment by kevin51jiang** [comment]
@fearme123123 

Got it to work! https://i.imgur.com/iI2vM1z.png

Time to do a bit more testing and get some JUnit tests done. Fix might be out later than expected.

**Comment by fearme123123** [comment]
@kevin51jiang Any update yet ?:)

**Pull request closed without merging**
