### PR TITLE
Make expanded window resizable

### PR DESCRIPTION
**Pull request by iqqu**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix (Fix #...)
* [ ] a new Ripper
* [x] a refactoring
* [ ] a style change/fix

# Description

The log, history, and queue are hard to read with a small unresizable window. This makes the window resizable when the lower panes are not visible.

# Testing
All the tests that fail also fail on the current main master branch. The failures are not related to these changes.

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [ ] Downloads all relevant content.
  * [ ] Downloads content from multiple pages (as necessary or appropriate).
  * [ ] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by iqqu** [comment]
The Java 1.8 update (#121) broke ripping. d4f83c0 is good.
I rebased my changes on #121 so if that is reverted I will push up my previous changes.

**Comment by cyian-1756** [comment]
Hey the 1.6.0 bug has been fixed

**Comment by iqqu** [comment]
I have rebased this branch on the latest master and it is ready to merge.

**Comment by cyian-1756** [comment]
> I have rebased this branch on the latest master and it is ready to merge.

Alright, I'll test this and merge it in once I have a free minute

**Comment by cyian-1756** [comment]
One issue with this, it seems to make the text bar were you enter the url you want to rip rather small, if you can increase the size of the back to what it is was (The same height as the rip button) then I'll merge

**Comment by iqqu** [comment]
I have pushed an update and this is ready for review. I also noticed a Linux bug related to this pull request and added a workaround.

**Comment by cyian-1756** [comment]
Looks alright to me, I did notice one minor issue tho, it seems that window isn't re-sizable until after you rip something. That being said it's not a blocking issue

**Comment by iqqu** [comment]
My intent was for the window to only be resizable when one of the lower panels is visible, so if you click on one of the lower buttons it should be resizable before ripping something (it works for me, at least).

We can make the window always resizable if the window only sometimes being resizable is confusing.

I just noticed that I was too hasty with my windowing bug fix: emptyPanel takes up space when expanding the window. I will create a pull request in a few minutes to fix that.

**Comment by cyian-1756** [comment]
> We can make the window always resizable if the window only sometimes being resizable is confusing.

I think that's best

**Pull request merged**
