### PR TITLE
Added Luscious.net ripper

### PR DESCRIPTION
**Pull request by cyian-1756**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix -- which issue? #...
* [X] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix

# Description

A ripper for the hentai site Luscious.net

# Testing

Required verification:
* [X] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [X] I've verified that this change works as intended.
  * [X] Downloads all relevant content.
  * [X] Downloads content from multiple pages (as necessary or appropriate).
  * [X] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [X] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by metaprime** [comment]
Testing with https://luscious.net/albums/huge-oppai_289560/ (NSFW)

**Comment by metaprime** [comment]
Generally looks good. Hit an error before reaching the end of the test rip. Trying again.

**Comment by metaprime** [comment]
I hit the error again:

`Error: No images found at https://luscious.net/c/hentai/pictures/album/huge-oppai_289560/id/17964925/@_106-pmsushk`

Didn't rip all the images in the album.

**Comment by cyian-1756** [comment]
My last push should fix everything

**Pull request merged**
