### PR TITLE
fix: instagramRipper, replaced Nashorn with GraalVM.js

### PR DESCRIPTION
**Pull request by cariah**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [x] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [ ] a new feature

# Description

This PR attempts to fix the instagramRipper, #1598 #1699 #1715 #1719 . I've replaced nashorn with GraalVM.js, which makes the binary a lot bigger. So I'm not sure how I feel about that.

Would appreciate your thoughts on this, perhaps a different way to reliably extract the qHash.

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [ ] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cariah** [comment]
Actually getting some errors on the /tagged Rips now, going to need to fix that one later.

**Comment by soloturn** [comment]
java15 removes nashorn anyway:
https://openjdk.java.net/jeps/372

i do not get errors for tagged, single download, album download. i did apply #1722 and the nashorn-graal switch from here.

**Comment by cariah** [comment]
Ah right, so I started testing a bit more and it seems to be a problem with authentication / private accounts.

**Comment by Tush-r** [comment]
Adding graaljs increases the size by 4x, but then again 15-20mb is not much.
I've tried a few different ways with nashorn, using babel polyfill, using IG's own `Polyfill.js`. Both did not work.
Using regex would be a dirty fix for now. 
Graal seems like the right way to go about it, which should also help with other modern sites.

@cyian-1756 can his input on this.

I'll test this today/ tomorrow.

**Comment by zxqro** [comment]
Thanks for this pull request. 
I checked it out and created a build with Maven - everything working fine for me.

**Comment by zxqro** [comment]
> Thanks for this pull request.
> I checked it out and created a build with Maven - everything working fine for me - both on Instagram & Reddit (haven't tested any other sites as for now, as I usually only use it for these 2.)

Oops... Noticed now that the config option "history.end_rip_after_already_seen" does not seem to properly work.
In the log it's clearly identifying files as already downloaded, but continues the rip of the URL long after the number defined in the config option has been passed. The reddit ripper still stops when it should.
The log is also looking different for Instagram compared to Reddit.
`https://scontent-prg1-1.cdninstagram.com/v/t51.2885-15/e35/11378731_101577923523667_932705012_n.jpg?_nc_ht=scontent-prg1-1.cdninstagram.com&_nc_cat=107&_nc_ohc=ncyXRtvTUaUAX9y_cMB&oh=999ebcece3f0ad0dfba452022997a9f1&oe=5F5EB56D already saved as D:\RipMe\instagram_celinasmith\2015-07-08_21-13-07_448t4KyJLS_11378731_101577923523667_932705012_n.jpg`

Compared to the message the reddit ripper gives:

`Already downloaded https://i.redd.it/js9xcqr2zux01.jpg`

**Comment by thinkpad4** [comment]
@cyian-1756 I hope this can get pushed soon

**Comment by soloturn** [comment]
@cyian-1756 what you think?

**Comment by cyian-1756** [comment]
Looks good to me. I'll test it and merge it for 1.8.0

**Comment by thinkpad4** [comment]
@cyian-1756 any update on when this well me merged?

**Comment by cyian-1756** [comment]
@cariah The ripper seems to be returning null for the query hash

**Comment by soloturn** [comment]
> @cariah The ripper seems to be returning null for the query hash

currently it does not work at all, would it not be a better option to merge it and then fix bugs if somebody notices? i, for example, am not sure about the link you see this null?

**Comment by soloturn** [comment]
@cyian-1756 ah, i understand, #1722 should fix this.

**Comment by cariah** [comment]
> 
> 
> @cariah The ripper seems to be returning null for the query hash

Sorry for being a little inactive.

Instagram seems to use these query hashes to cache queries orsomething. Might be a better way to get rid of the JS parsing entirely and hardcode these query hashes and periodicly update them when/if they break (would also mean old instagram clients break). It also prevents people from getting random errors, because everyone is using the same hashes. Thoughts?

**Comment by Tush-r** [comment]
> > @cariah The ripper seems to be returning null for the query hash
> 
> Sorry for being a little inactive.
> 
> Instagram seems to use these query hashes to cache queries orsomething. Might be a better way to get rid of the JS parsing entirely and hardcode these query hashes and periodicly update them when/if they break (would also mean old instagram clients break). It also prevents people from getting random errors, because everyone is using the same hashes. Thoughts?

The current error after this merge is to do with the regex catching the wrong text as query hash. 
I'll get the fix out in few days.
I don't think its possible to hardcode the query hashes. I think  they would be unique per request, profile or something.

**Comment by soloturn** [comment]
@cariah @Tush-r @cyian-1756 you are saying despite merging  #1722 it fails? can you post a url where this is so?

**Comment by Tush-r** [comment]
> @cariah @Tush-r @cyian-1756 cannot reproduce an error here. you are saying despite merging #1722 it fails for you? can you post a url where this is so?

Sorry. I previous reply mentions an error but there is an issue( and not error). The ripper now only rips the first page. This is due to the query hash regex catching the wrong text.
The issue is mentioned in latest replies for #1740 
I do have a fix for it, just need to test it. I'll get it out latest by tomorrow.

**Pull request merged**
