### PR TITLE
Change folder name in imagearn

### PR DESCRIPTION
**Pull request by EgorGornak**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [x] a style change/fix (Issue #280)

# Description

Change folder name in imagearn from imagearn_id to imagearn_name.
Before: "imagearn_106462".
Now "imagearn_Varias_Da_Boua".

# Testing

Required verification:
* [x] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [x] Downloads all relevant content.
  * [x] Downloads content from multiple pages (as necessary or appropriate).
  * [x] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by cyian-1756** [comment]
Could you make the folder title also include the GID? It helps stop problems when downloading 2 different albums of the same name

**Comment by EgorGornak** [comment]
Done!

**Comment by cyian-1756** [comment]
LGTM

**Comment by cyian-1756** [comment]
In the future be sure to fill in the issue number (a bug fix (Fix #$Issue_number_goes_here)) as it will auto close the issue when the PR is merged into master.

**Pull request merged**
