### PR TITLE
fix xhamster testGetNextPage

### LINKED ISSUE #1777: Xhamster photo galleries stopping download at 24 images.
* Ripme version: 1.7.93
* Java version: 8_172
* Operating system: Windows 7
* Exact URL you were trying to rip when the problem occurred: https://xhamster.com/photos/gallery/sawaki-mayumi-11023311
* Please include any additional information about how to reproduce the problem: This just started today and was working fine yesterday with 1 dropped image every few galleries with nothing changed on my end so it may have been something on xhamster's side that is causing the issue.

## Expected Behavior

Expecting all 52 images of the gallery to be ripped.

## Actual Behavior

Only 24 images are downloaded before it reports it as complete despite the gallery containing more images. Many galleries I have tried from Xhamster photo have had the same problem.

### PR DESCRIPTION
**Pull request by soloturn**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ x] a bug fix (Fix #...)
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [ ] a new feature

# Description
fix xhamster getTestNextPage, copy 2 lines change from #1798, fix #1777, #1735.

# Testing
xhamster unit test now green.

### CODE REVIEW

**Comment by soloturn** [comment]
tests were still not green but depending on the build agent. mark the ones failing as "flaky".

**Comment by soloturn** [comment]
fix #1735.

**Comment by soloturn** [comment]
@cyian-1756 anything missing with this one?

**Comment by cyian-1756** [comment]
LGTM, sorry for taking so long to get to this

**Pull request merged**
