### PR TITLE
Issues/1402 confirm clear

### LINKED ISSUE #1402: Request: CONFIRM DIALOG FOR QUEUE CLEAR AND QUEUE AUTOSAVE.
* Ripme version: 1.7.86

Could we please implement a simple "Are you sure" dialog for clearing the queue? I accidentally cleared my queue because the "remove selected" and "remove all" option is very close together. This is beyond irritating.

Also, could we implement queue autosave not when the program is closed but after each URL? I hate waiting for an URL to finish ripping so the queue is updated when I close it, not to mention the annoyances that occur when you make a mistake of moving the cursor ever so slightly down and click on Remove All menu, which clears the queue in the memory and blanks out the data.

(Note: The queue is only updated when you hit Stop and close the program. Useless when your queue is vaporized because your mouse jittered while trying to remove links that don't make sense.)

### PR DESCRIPTION
**Pull request by Isaaku**
# Category

This change is exactly one of the following (please change `[ ]` to `[x]`) to indicate which:
* [ ] a bug fix 
* [ ] a new Ripper
* [ ] a refactoring
* [ ] a style change/fix
* [X] a new feature (Fix #1402 )

# Description

Added confirmation when click in remove all

# Testing

Required verification:
* [ ] I've verified that there are no regressions in `mvn test` (there are no new failures or errors).
* [x] I've verified that this change works as intended.
  * [ ] Downloads all relevant content.
  * [ ] Downloads content from multiple pages (as necessary or appropriate).
  * [ ] Saves content at reasonable file names (e.g. page titles or content IDs) to help easily browse downloaded content.
* [x] I've verified that this change did not break existing functionality (especially in the Ripper I modified).

Optional but recommended:
* [ ] I've added a unit test to cover my change.

### CODE REVIEW

**Comment by Isaaku** [comment]
Need to be merged after https://github.com/RipMeApp/ripme/pull/1406#issue-307439320

**Comment by Isaaku** [comment]
@cyian-1756  this is ready to merge to master

**Comment by cyian-1756** [comment]
Testing this out a bit it looks like it causes a UI error. The Queue button never resets even when the Queue is empty

**Comment by Isaaku** [comment]
Ok, let me take a look

**Comment by Isaaku** [comment]
Fix in https://github.com/RipMeApp/ripme/pull/1423

**Pull request merged**
